node('nodejs') {
  stage 'build'
  openshiftBuild(buildConfig: 'node-app-with-prometheus-metrics', showBuildLogs: 'true')
  stage 'deploy'
  openshiftDeploy(deploymentConfig: 'node-app-with-prometheus-metrics')
}
